//
// Created by Jamar Slave on 16/12/2019.
//

#include "inc/ft_printf.h"

int         main()///2468//284/306
{
	int t;

/*
	printf("mine:\n");
	t = ft_printf("%1.i|%-1.i|%+1.i|% 1.i|%01.i", LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%1.i|%-1.i|%+1.i|% 1.i|%01.i", LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n1------------\n");
	printf("mine:\n");
	t = ft_printf("%-+23i|%- 23i|%-023i|%+ 23i|%+023i|% 023i|%-+ 023i", LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+23i|%- 23i|%-023i|%+ 23i|%+023i|% 023i|%-+ 023i", LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n2------------\n");
	printf("mine:\n");
	t = ft_printf("%-+1.i|%- 1.i|%-01.i|%+ 1.i|%+01.i|% 01.i|%-+ 01.i", LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+1.i|%- 1.i|%-01.i|%+ 1.i|%+01.i|% 01.i|%-+ 01.i", LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN, LONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n3------------\n");
	printf("mine:\n");
	t = ft_printf("%1.i|%-1.i|%+1.i|% 1.i|%01.i", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%1.i|%-1.i|%+1.i|% 1.i|%01.i", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n4------------\n");
	printf("mine:\n");
	t = ft_printf("%-+23i|%- 23i|%-023i|%+ 23i|%+023i|% 023i|%-+ 023i", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+23i|%- 23i|%-023i|%+ 23i|%+023i|% 023i|%-+ 023i", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n5------------\n");
	printf("mine:\n");
	t = ft_printf("%-+1.i|%- 1.i|%-01.i|%+ 1.i|%+01.i|% 01.i|%-+ 01.i", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+1.i|%- 1.i|%-01.i|%+ 1.i|%+01.i|% 01.i|%-+ 01.i", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n6------------\n");
	printf("mine:\n");
	t = ft_printf("%1.hhi|%-1.hhi|%+1.hhi|% 1.hhi|%01.hhi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%1.hhi|%-1.hhi|%+1.hhi|% 1.hhi|%01.hhi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n7------------\n");
	printf("mine:\n");
	t = ft_printf("%-+23hhi|%- 23hhi|%-023hhi|%+ 23hhi|%+023hhi|% 023hhi|%-+ 023hhi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+23hhi|%- 23hhi|%-023hhi|%+ 23hhi|%+023hhi|% 023hhi|%-+ 023hhi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n8------------\n");
	printf("mine:\n");
	t = ft_printf("%-+1.hhi|%- 1.hhi|%-01.hhi|%+ 1.hhi|%+01.hhi|% 01.hhi|%-+ 01.hhi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+1.hhi|%- 1.hhi|%-01.hhi|%+ 1.hhi|%+01.hhi|% 01.hhi|%-+ 01.hhi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n9------------\n");
	printf("mine:\n");
	t = ft_printf("%1.hi|%-1.hi|%+1.hi|% 1.hi|%01.hi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%1.hi|%-1.hi|%+1.hi|% 1.hi|%01.hi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n10------------\n");
	printf("mine:\n");
	t = ft_printf("%-+23hi|%- 23hi|%-023hi|%+ 23hi|%+023hi|% 023hi|%-+ 023hi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+23hi|%- 23hi|%-023hi|%+ 23hi|%+023hi|% 023hi|%-+ 023hi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n11------------\n");
	printf("mine:\n");
	t = ft_printf("%-+1.hi|%- 1.hi|%-01.hi|%+ 1.hi|%+01.hi|% 01.hi|%-+ 01.hi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+1.hi|%- 1.hi|%-01.hi|%+ 1.hi|%+01.hi|% 01.hi|%-+ 01.hi", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n12------------\n");
	printf("mine:\n");
	t = ft_printf("%23li|%-23li|%+23li|% 23li|%023li", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%23li|%-23li|%+23li|% 23li|%023li", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n13------------\n");
	printf("mine:\n");
	t = ft_printf("%23.li|%-23.li|%+23.li|% 23.li|%023.li", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%23.li|%-23.li|%+23.li|% 23.li|%023.li", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n14------------\n");
	printf("mine:\n");
	t = ft_printf("%-+23li|%- 23li|%-023li|%+ 23li|%+023li|% 023li|%-+ 023li", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+23li|%- 23li|%-023li|%+ 23li|%+023li|% 023li|%-+ 023li", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n15------------\n");
	printf("mine:\n");
	t = ft_printf("%-+23.li|%- 23.li|%-023.li|%+ 23.li|%+023.li|% 023.li|%-+ 023.li", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+23.li|%- 23.li|%-023.li|%+ 23.li|%+023.li|% 023.li|%-+ 023.li", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n16------------\n");
	printf("mine:\n");
	t = ft_printf("%23lli|%-23lli|%+23lli|% 23lli|%023lli", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%23lli|%-23lli|%+23lli|% 23lli|%023lli", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n17------------\n");
	printf("mine:\n");
	t = ft_printf("%23.lli|%-23.lli|%+23.lli|% 23.lli|%023.lli", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%23.lli|%-23.lli|%+23.lli|% 23.lli|%023.lli", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n18------------\n");
	printf("mine:\n");
	t = ft_printf("%-+23lli|%- 23lli|%-023lli|%+ 23lli|%+023lli|% 023lli|%-+ 023lli", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+23lli|%- 23lli|%-023lli|%+ 23lli|%+023lli|% 023lli|%-+ 023lli", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n19------------\n");

	printf("mine:\n");
	t = ft_printf("%-+23.lli|%- 23.lli|%-023.lli|%+ 23.lli|%+023.lli|% 023.lli|%-+ 023.lli", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("%-+23.lli|%- 23.lli|%-023.lli|%+ 23.lli|%+023.lli|% 023.lli|%-+ 023.lli", LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN, LLONG_MIN);
	printf("<-\nreturned value : %i", t);
	printf("\n20------------\n");
 */
	printf("mine:\n");
	t = ft_printf("% lli", 9223372036854775807ll);
	printf("<-\nreturned value : %i", t);
	printf("\norigin:\n");
	t = printf("% lli", 9223372036854775807ll);
	printf("<-\nreturned value : %i", t);
	printf("\n20------------\n");
	return (0);
}

